import { ImageAsset } from '../types';

export const assetMap: Record<string, ImageAsset> = {
  hero: {
    id: 'hero-main',
    url: 'https://images.unsplash.com/photo-1438232992991-995b7058bbb3?auto=format&fit=crop&q=80&w=2000',
    alt: 'Worship congregation lifting hands in adoration at Church of God Subic',
    title: 'Church of God Subic Worship',
    category: 'hero',
  },
  welcome: {
    id: 'welcome-community',
    url: 'https://images.unsplash.com/photo-1511632765486-a01980e01a18?auto=format&fit=crop&q=80&w=1200',
    alt: 'Church community welcoming new members with warm hospitality',
    title: 'Warm Church Community',
    category: 'community',
  },
  pastor: {
    id: 'lead-pastor',
    url: 'https://images.unsplash.com/photo-1507003211169-0a1dd7228f2d?auto=format&fit=crop&q=80&w=800',
    alt: 'Lead Pastor delivering an inspiring message',
    title: 'Lead Pastor',
    category: 'leadership',
  },
  sermonFeatured: {
    id: 'sermon-featured',
    url: 'https://images.unsplash.com/photo-1470225620780-dba8ba36b745?auto=format&fit=crop&q=80&w=1200',
    alt: 'Pastor speaking on stage with backdrop during Sunday worship service',
    title: 'Sunday Worship Message',
    category: 'sermon',
  },
  prayerBg: {
    id: 'prayer-bg',
    url: 'https://images.unsplash.com/photo-1499209974431-9dddcece7f88?auto=format&fit=crop&q=80&w=1600',
    alt: 'Serene atmosphere of prayer and quiet reflection',
    title: 'Prayer and Quiet Reflection',
    category: 'background',
  },
  gospelBg: {
    id: 'gospel-bg',
    url: 'https://images.unsplash.com/photo-1519817650390-64a93db51149?auto=format&fit=crop&q=80&w=1600',
    alt: 'Cross illuminated by dramatic sunlight over serene hills',
    title: 'Hope in Jesus Christ',
    category: 'background',
  },
  worshipMinistry: {
    id: 'min-worship',
    url: 'https://images.unsplash.com/photo-1514525253161-7a46d19cd819?auto=format&fit=crop&q=80&w=800',
    alt: 'Worship team band leading music with acoustic guitar and praise',
    title: 'Worship Ministry',
    category: 'ministry',
  },
  youthMinistry: {
    id: 'min-youth',
    url: 'https://images.unsplash.com/photo-1529156069898-49953e39b3ac?auto=format&fit=crop&q=80&w=800',
    alt: 'Youth group gathering in joyful fellowship and group discussion',
    title: 'Youth Ministry',
    category: 'ministry',
  },
  childrenMinistry: {
    id: 'min-kids',
    url: 'https://images.unsplash.com/photo-1485546246426-74dc88dec4d9?auto=format&fit=crop&q=80&w=800',
    alt: 'Children engaged in Bible story activities and creative crafts',
    title: 'Kingdom Kids Ministry',
    category: 'ministry',
  },
  outreachMinistry: {
    id: 'min-outreach',
    url: 'https://images.unsplash.com/photo-1488521787991-ed7bbaae773c?auto=format&fit=crop&q=80&w=800',
    alt: 'Community food outreach team serving families with love',
    title: 'Community Outreach',
    category: 'ministry',
  },
  discipleshipMinistry: {
    id: 'min-discipleship',
    url: 'https://images.unsplash.com/photo-1522202176988-66273c2fd55f?auto=format&fit=crop&q=80&w=800',
    alt: 'Small group Bible study meeting in a warm living room environment',
    title: 'Life Groups & Discipleship',
    category: 'ministry',
  },
  couplesMinistry: {
    id: 'min-couples',
    url: 'https://images.unsplash.com/photo-1516589178581-6cd7833ae3b2?auto=format&fit=crop&q=80&w=800',
    alt: 'Couples fellowship workshop supporting strong Christian marriages',
    title: 'Family & Marriage Ministry',
    category: 'ministry',
  },
  churchSubic: {
    id: 'church-subic',
    url: 'https://images.unsplash.com/photo-1548625149-fc4a29cf7092?auto=format&fit=crop&q=80&w=800',
    alt: 'Church of God Subic main sanctuary building entrance',
    title: 'Subic Main Sanctuary',
    category: 'church',
  },
  churchOlongapo: {
    id: 'church-olongapo',
    url: 'https://images.unsplash.com/photo-1438032005730-c779502df39b?auto=format&fit=crop&q=80&w=800',
    alt: 'Church of God Olongapo worship hall',
    title: 'Olongapo Location',
    category: 'church',
  },
  churchCastillejos: {
    id: 'church-castillejos',
    url: 'https://images.unsplash.com/photo-1438032005730-c779502df39b?auto=format&fit=crop&q=80&w=800',
    alt: 'Church of God Castillejos location',
    title: 'Castillejos Location',
    category: 'church',
  },
};
