/**
 * Project Nehemiah — Role-Permission Matrix Configuration
 * Centralized mapping of canonical technical roles to granular permissions.
 */

import { AdminRole, Permission } from '../types/rbac';

export const ALL_PERMISSIONS: Permission[] = [
  'dashboard.read',
  'pages.read',
  'pages.create',
  'pages.update',
  'pages.publish',
  'ministries.read',
  'ministries.create',
  'ministries.update',
  'ministries.publish',
  'sermons.read',
  'sermons.create',
  'sermons.update',
  'sermons.publish',
  'events.read',
  'events.create',
  'events.update',
  'events.publish',
  'churches.read',
  'churches.update',
  'churches.publish',
  'leadership.read',
  'leadership.update',
  'leadership.publish',
  'media.read',
  'media.upload',
  'media.update',
  'media.delete',
  'prayer.read',
  'prayer.update',
  'contact.read',
  'contact.update',
  'governance.read',
  'governance.review',
  'governance.publish',
  'settings.read',
  'settings.update',
  'branding.read',
  'branding.update',
  'users.read',
  'users.manage',
  'audit.read',
];

export const ROLE_PERMISSIONS: Record<AdminRole, Permission[]> = {
  SUPER_ADMIN: [...ALL_PERMISSIONS],

  ADMIN: [
    'dashboard.read',
    'pages.read',
    'pages.create',
    'pages.update',
    'pages.publish',
    'ministries.read',
    'ministries.create',
    'ministries.update',
    'ministries.publish',
    'sermons.read',
    'sermons.create',
    'sermons.update',
    'sermons.publish',
    'events.read',
    'events.create',
    'events.update',
    'events.publish',
    'churches.read',
    'churches.update',
    'churches.publish',
    'leadership.read',
    'leadership.update',
    'leadership.publish',
    'media.read',
    'media.upload',
    'media.update',
    'media.delete',
    'contact.read',
    'contact.update',
    'governance.read',
    'governance.review',
    'governance.publish',
    'settings.read',
    'settings.update',
    'branding.read',
    'branding.update',
    'users.read',
    'audit.read',
  ],

  EDITOR: [
    'dashboard.read',
    'pages.read',
    'pages.create',
    'pages.update',
    'pages.publish',
    'ministries.read',
    'ministries.create',
    'ministries.update',
    'ministries.publish',
    'sermons.read',
    'sermons.create',
    'sermons.update',
    'sermons.publish',
    'events.read',
    'events.create',
    'events.update',
    'events.publish',
    'churches.read',
    'churches.update',
    'leadership.read',
    'leadership.update',
    'media.read',
    'media.upload',
  ],

  MEDIA_ADMIN: [
    'dashboard.read',
    'sermons.read',
    'sermons.create',
    'sermons.update',
    'sermons.publish',
    'media.read',
    'media.upload',
    'media.update',
    'media.delete',
  ],

  PRAYER_ADMIN: [
    'dashboard.read',
    'prayer.read',
    'prayer.update',
  ],

  MINISTRY_EDITOR: [
    'dashboard.read',
    'ministries.read',
    'ministries.create',
    'ministries.update',
    'ministries.publish',
    'events.read',
    'events.create',
    'events.update',
  ],

  READ_ONLY: [
    'dashboard.read',
    'pages.read',
    'ministries.read',
    'sermons.read',
    'events.read',
    'churches.read',
    'leadership.read',
    'media.read',
    'governance.read',
    'settings.read',
    'branding.read',
    'audit.read',
  ],
};

/**
 * Resolves permissions for a given role, falling back to empty array if unknown.
 */
export function getPermissionsForRole(role: AdminRole | null | undefined): Permission[] {
  if (!role) return [];
  return ROLE_PERMISSIONS[role] || [];
}
